# Generated by Django 3.0.7 on 2020-06-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explorer',
            name='block_value',
        ),
    ]
