# Generated by Django 3.0.8 on 2020-07-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200722_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='coin',
            field=models.CharField(default='EPIC', max_length=124),
        ),
        migrations.AlterField(
            model_name='history',
            name='pair',
            field=models.CharField(default=('usdt', 'usdt'), max_length=100),
        ),
    ]
