# Generated by Django 3.0.8 on 2020-07-20 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=50)),
                ('amount', models.FloatField(default='9')),
                ('price', models.FloatField(default='1.3')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('distance', models.CharField(blank=True, max_length=20)),
                ('time', models.CharField(blank=True, max_length=15)),
                ('cost', models.CharField(blank=True, max_length=15)),
                ('dest_link', models.URLField(blank=True)),
                ('origin_link', models.URLField(blank=True)),
                ('destination_full', models.CharField(blank=True, max_length=50)),
                ('origin_full', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
